name: Pull Requests

on:
  pull_request:

permissions:
  # Required for CodeQL security scanning
  security-events: write
  # Required for private repositories
  actions: read
  contents: read

jobs:
  pull-request:
    strategy:
      fail-fast: true
      matrix:
        charm-path:
          - coordinator
          - worker
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@main
    secrets: inherit
    with:
      provider: k8s
      charm-path: ${{ matrix.charm-path }}
      enable-integration: ${{ matrix.charm-path == 'coordinator' }}
      juju-channel: 3.6/candidate
